site_name: Open Restaurant 2.x.x
theme: readthedocs
repo_url: https://github.com/openrestaurant/docs
include_search: true
extra_css:
  - assets/css/style.css
pages:
- Home: index.md
- Installation: installation.md
- Theming: theming.md
- Development: development.md
